version: '3.4'

services:
    postgres:
        image: postgres
        container_name: my_postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: threads
            POSTGRES_DB: threads_db
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis
        container_name: my_redis
        restart: always
        ports:
            - "6379:6379"

volumes:
    postgres_data:
