version: '3.4'

services:
    postgres:
        image: postgres
        container_name: thread_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: threads
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
